### ISSUE TITLE
Build with gcc 5.4.0 error

### ISSUE THREAD

**Issue by wangguibao** [PaddlePaddle/Serving#88]
System: 16.04.6 LTS (Xenial Xerus)
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 

Error message:
```
In file included from /usr/include/c++/5/bits/ios_base.h:41:0,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iterator:64,
                 from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/detail/iterator.hpp:54,
                 from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/iterator/iterator_categories.hpp:10,
                 from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/unordered/detail/table.hpp:14,
                 from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/unordered/detail/equivalent.hpp:10,
                 from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/unordered/unordered_map.hpp:19,
                 from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/unordered_map.hpp:16,
                 from /home/tangzhiyi01/ctr/Serving/sdk-cpp/include/common.h:26,
                 from /home/tangzhiyi01/ctr/Serving/sdk-cpp/include/config_manager.h:18,
                 from /home/tangzhiyi01/ctr/Serving/sdk-cpp/src/config_manager.cpp:15:
/usr/include/c++/5/bits/locale_classes.h:284:24: error: reference to ‘basic_string’ is ambiguous
       operator()(const basic_string<_Char, _Traits, _Alloc>& __s1,
                        ^
In file included from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/functional/hash/extensions.hpp:17:0,
                 from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/functional/hash/hash.hpp:477,
                 from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/functional/hash.hpp:6,
                 from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/unordered/unordered_map.hpp:17,
                 from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/unordered_map.hpp:16,
                 from /home/tangzhiyi01/ctr/Serving/sdk-cpp/include/common.h:26,
                 from /home/tangzhiyi01/ctr/Serving/sdk-cpp/include/config_manager.h:18,
                 from /home/tangzhiyi01/ctr/Serving/sdk-cpp/src/config_manager.cpp:15:
/home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/detail/container_fwd.hpp:61:65: note: candidates are: template<class charT, class traits, class Allocator> class std::basic_string
     template <class charT, class traits, class Allocator> class basic_string;
                                                                 ^
In file included from /usr/include/c++/5/string:39:0,
                 from /usr/include/c++/5/stdexcept:39,
                 from /usr/include/c++/5/array:38,
                 from /usr/include/c++/5/tuple:39,
                 from /usr/include/c++/5/bits/stl_map.h:63,
                 from /usr/include/c++/5/map:61,
                 from /home/tangzhiyi01/ctr/Serving/sdk-cpp/include/config_manager.h:16,
                 from /home/tangzhiyi01/ctr/Serving/sdk-cpp/src/config_manager.cpp:15:
/usr/include/c++/5/bits/stringfwd.h:71:11: note:                 template<class _CharT, class _Traits, class _Alloc> class std::__cxx11::basic_string
     class basic_string;
           ^
In file included from /usr/include/c++/5/bits/ios_base.h:41:0,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iterator:64,
                 from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/detail/iterator.hpp:54,
                 from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/iterator/iterator_categories.hpp:10,
                 from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/unordered/detail/table.hpp:14,
                 from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/unordered/detail/equivalent.hpp:10,
                 from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/unordered/unordered_map.hpp:19,
                 from /home/tangzhiyi01/ctr/Serving/build/third_party/boost/src/extern_boost/boost/unordered_map.hpp:16,
                 from /home/tangzhiyi01/ctr/Serving/sdk-cpp/include/common.h:26,
                 from /home/tangzhiyi01/ctr/Serving/sdk-cpp/include/config_manager.h:18,
                 from /home/tangzhiyi01/ctr/Serving/sdk-cpp/src/config_manager.cpp:15:
/usr/include/c++/5/bits/locale_classes.h:284:36: error: expected ‘,’ or ‘...’ before ‘<’ token
       operator()(const basic_string<_Char, _Traits, _Alloc>& __s1,
```
